### ISSUE TITLE
高亮显示思路

### ISSUE THREAD

**Issue by happypeter** [happypeter/a-haoqicat#7]
https://github.com/happypeter/a-haoqicat/issues/3 相关

每次一行完成，把新的代码交给人家的高亮引擎，转换车带标签的字符串，显示到咱们自己的界面上。

不要自己手写正则表达式去实现高亮，那样相当于重新实现一般高亮引擎，工作量巨大。

我这个思路估计对高亮引擎的接口性能要求也比较高，不知道能不能实现。

**Comment by billie66** [comment]
我试一下

**Comment by billie66** [comment]
打印完一行，然后调用 prism.js 库的接口可以实现代码高亮，prims.js 会根据代码类型自动添加标签
